### ISSUE TITLE
Cannot be imported on Python 3.6, because of keyword-only argument inspection

### ISSUE THREAD

**Issue by jmoldow** [stefankoegl/python-json-patch#56]
jsonpatch==1.14 on Python 3.6 cannot be imported.

It fails with the following stacktrace:

```python
      .tox/py/lib/python3.6/site-packages/jsonpatch.py:114: in <module>
          json.load = get_loadjson()
      .tox/py/lib/python3.6/site-packages/jsonpatch.py:108: in get_loadjson
          argspec = inspect.getargspec(json.load)
      lib/python3.6/inspect.py:1039: in getargspec
          raise ValueError("Function has keyword-only arguments or annotations"
      E   ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

The error message is a bit misleading. In Python >=3.5, `inspect.getfullargspec()` is also deprecated, in favor of `inspect.signature()`.

https://docs.python.org/3.6/library/inspect.html#inspect.getfullargspec

This happened because Python 3.6 changed all optional arguments to be keyword-only.

https://docs.python.org/3.6/library/json.html#json.load

**Comment by jmoldow** [comment]
Never mind, I see this was already fixed in master, just not released to PyPI yet. Thanks!

**Comment by usamamashkoor** [comment]
I am still facing the issue with python 3.6 this is the error which i am facing 
`No matching distribution found for cloud-init==17.2 (from -r requirements.txt (line 13))`
